# docker-compose.yml
# NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose -f ./compose/ws.yml up -d
services:
  napcat:
    image: mlikiowa/napcat-docker:v4.17.5
    container_name: napcat
    restart: always
    mac_address: 02:42:ac:11:00:02

    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
      - ACCOUNT=${ACCOUNT}

    ports:
      - 3001:3001
      - 6099:6099

    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=${PG_PASSWORD:-bot123}
      - POSTGRES_DB=bot
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    image: qq-bot:0.0.1
    container_name: bot
    restart: always
    mac_address: 02:42:ac:11:00:03

    environment:
      - NAPCAT_WS_URL=ws://napcat:3001
      - DATABASE_URL=postgres://bot:${PG_PASSWORD:-bot123}@postgres:5432/bot
      - NAPCAT_ACCESS_TOKEN=${NAPCAT_ACCESS_TOKEN}
      - JISU_API_TOKEN=${JISU_API_TOKEN}
      - GOLD_API_TOKEN=${GOLD_API_TOKEN}
      - CURRENCY_RATES_API_TOKEN=${CURRENCY_RATES_API_TOKEN}

      - OPENAI_BASE_URL=
      - OPENAI_API_KEY=
      - OPENAI_API_MODEL=

      - COMFY_UI_URL=${COMFY_UI_URL}
      - EMBEDDING_URL=http://host.docker.internal:8080

    depends_on:
      - napcat
      - postgres
