[package]
name = "bot_run"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bot_lib = { path = "../bot_lib" }
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
log.workspace = true
env_logger.workspace = true
dotenvy.workspace = true

reqwest = { version = "0.13.2", features = [
    "json",
    "native-tls",
], default-features = false }
sha2 = "0.11"
image = "0.25"
imagehash = { git = "https://github.com/takebayashi/imagehash-rs" }
base64 = "0.22"
chrono.workspace = true
once_cell.workspace = true
thiserror.workspace = true
async-trait.workspace = true
rand = "0.10.1"
tempfile.workspace = true
num-traits = "0.2.19"
num-bigint = "0.4.6"
html2text = "0.17"
resvg = "0.47"
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "uuid",
    "chrono",
] }
uuid = { version = "1", features = ["v4", "serde"] }
